from app.db.base_class import Base  # noqa
from app.models.address import Base # noqa
from app.models.company import Base # noqa
from app.models.department import Base # noqa
from app.models.employment import Base # noqa
from app.models.position import Base # noqa
from app.models.role import Base  # noqa
from app.models.user import Base  # noqa
from app.models.user_address import Base # noqa
from app.models.user_company import Base # noqa
from app.models.user_department import Base # noqa
from app.models.user_employment import Base # noqa
from app.models.user_managers import Base # noqa
from app.models.user_positions import Base # noqa
from app.models.user_roles import Base # noqa
from app.models.user_schedules import Base # noqa
from app.models.user_workhours import Base # noqa
